- name: "Download Apache Tomcat 9.0 Archive"
  get_url:
    url:  http://www-us.apache.org/dist/tomcat/tomcat-9/v9.0.6/bin/apache-tomcat-9.0.6.tar.gz
    dest: "{{apache_install_location}}"
    force: no
  become: yes

- name: "Unzipping Apache Tomcat Archive"
  unarchive:
    src: "{{apache_install_location}}/{{apache_file_name}}.tar.gz"
    dest: /usr/local/
    remote_src: yes
  become: yes

- name: "Removing previous Apache Tomcat instances"
  file:
    path: "{{apache_install_location}}/tomcat9"
    state: absent
  become: true

- name: "Renaming Apache Tomcat Directory"
  command: mv {{apache_install_location}}/{{apache_file_name}} {{apache_install_location}}/tomcat9
  become: yes

- name: "Setting up user for Apache Tomcat"
  template: src=apache_template.xml.j2 dest={{ apache_install_location }}/tomcat9/conf/tomcat-users.xml
  become: yes

# - name: "Setting up Apache Tomcat Variables"
#   shell: echo "export CATALINA_HOME="{{apache_install_location}}/tomcat9"" >> /etc/environment
#   become: yes
# - shell: echo "export JAVA_HOME="/usr/lib/jvm/java-8-oracle"" >> /etc/environment
#   become: yes
# - shell: echo "export JRE_HOME="/usr/lib/jvm/java-8-oracle/jre"" >> /etc/environment
#   become: yes

- name: "Starting Apache server"
  command: nohup {{ apache_install_location }}/tomcat9/bin/startup.sh
  become: yes
